"""Built-in local command definitions for offline/fallback mode."""

LOCAL_COMMANDS = [
    # Kernel
    {
        "keywords": ["disable", "transparent", "hugepages", "thp"],
        "description": "Disable transparent hugepages (runtime + persistent via grub)",
        "category": "kernel",
        "commands": [
            "echo never > /sys/kernel/mm/transparent_hugepage/enabled",
            "echo never > /sys/kernel/mm/transparent_hugepage/defrag",
            "grubby --update-kernel=ALL --args='transparent_hugepage=never'",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Runtime change is immediate. Grub change persists across reboots.",
    },
    {
        "keywords": ["enable", "transparent", "hugepages", "thp"],
        "description": "Enable transparent hugepages",
        "category": "kernel",
        "commands": [
            "echo always > /sys/kernel/mm/transparent_hugepage/enabled",
            "grubby --update-kernel=ALL --remove-args='transparent_hugepage=never'",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Runtime change is immediate. Grub change persists across reboots.",
    },
    {
        "keywords": ["load", "kernel", "module"],
        "description": "Load a kernel module",
        "category": "kernel",
        "commands": ["modprobe <module_name>"],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <module_name> with the actual module. Use 'lsmod' to list loaded modules.",
    },
    {
        "keywords": ["unload", "remove", "kernel", "module"],
        "description": "Unload a kernel module",
        "category": "kernel",
        "commands": ["modprobe -r <module_name>"],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <module_name> with the actual module.",
    },
    {
        "keywords": ["list", "kernel", "modules", "loaded"],
        "description": "List loaded kernel modules",
        "category": "kernel",
        "commands": ["lsmod"],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["sysctl", "kernel", "parameters"],
        "description": "Show all sysctl kernel parameters",
        "category": "kernel",
        "commands": ["sysctl -a"],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["enable", "sysrq"],
        "description": "Enable SysRq key (runtime + persistent)",
        "category": "kernel",
        "commands": [
            "sysctl -w kernel.sysrq=1",
            "echo 'kernel.sysrq = 1' >> /etc/sysctl.d/99-sysrq.conf",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Enables all SysRq functions. Use a bitmask value (e.g. 176) to enable only specific functions.",
    },
    {
        "keywords": ["disable", "sysrq"],
        "description": "Disable SysRq key (runtime + persistent)",
        "category": "kernel",
        "commands": [
            "sysctl -w kernel.sysrq=0",
            "echo 'kernel.sysrq = 0' >> /etc/sysctl.d/99-sysrq.conf",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["check", "sysrq", "status"],
        "description": "Check current SysRq setting",
        "category": "kernel",
        "commands": ["sysctl kernel.sysrq"],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    # Kdump
    {
        "keywords": ["configure", "kdump", "setup"],
        "description": "Configure and enable kdump crash recovery",
        "category": "kernel",
        "commands": [
            "yum install -y kexec-tools",
            "systemctl enable kdump",
            "systemctl start kdump",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Kdump requires reserved memory. Check /etc/kdump.conf for settings.",
    },
    {
        "keywords": ["disable", "kdump"],
        "description": "Disable kdump crash recovery",
        "category": "kernel",
        "commands": [
            "systemctl stop kdump",
            "systemctl disable kdump",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["check", "status", "kdump"],
        "description": "Check kdump status",
        "category": "kernel",
        "commands": [
            "systemctl status kdump",
            "kdumpctl status",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    # SELinux
    {
        "keywords": ["disable", "selinux"],
        "description": "Disable SELinux (requires reboot for full effect)",
        "category": "security",
        "commands": [
            "setenforce 0",
            "sed -i 's/^SELINUX=.*/SELINUX=disabled/' /etc/selinux/config",
        ],
        "risk_level": "high",
        "requires_reboot": True,
        "notes": "WARNING: Disabling SELinux reduces system security. Reboot required for permanent change.",
    },
    {
        "keywords": ["enable", "selinux"],
        "description": "Enable SELinux in enforcing mode",
        "category": "security",
        "commands": [
            "sed -i 's/^SELINUX=.*/SELINUX=enforcing/' /etc/selinux/config",
        ],
        "risk_level": "high",
        "requires_reboot": True,
        "notes": "Reboot required. Run 'fixfiles -F onboot' if re-enabling after being disabled.",
    },
    {
        "keywords": ["check", "status", "selinux"],
        "description": "Check SELinux status",
        "category": "security",
        "commands": ["getenforce", "sestatus"],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["permissive", "selinux"],
        "description": "Set SELinux to permissive mode",
        "category": "security",
        "commands": [
            "setenforce 0",
            "sed -i 's/^SELINUX=.*/SELINUX=permissive/' /etc/selinux/config",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Permissive mode logs violations but does not enforce. Persistent via config.",
    },
    # Firewall
    {
        "keywords": ["disable", "firewall", "firewalld"],
        "description": "Disable firewalld",
        "category": "security",
        "commands": [
            "systemctl stop firewalld",
            "systemctl disable firewalld",
        ],
        "risk_level": "high",
        "requires_reboot": False,
        "notes": "WARNING: Disabling the firewall exposes all ports.",
    },
    {
        "keywords": ["enable", "firewall", "firewalld"],
        "description": "Enable firewalld",
        "category": "security",
        "commands": [
            "systemctl enable firewalld",
            "systemctl start firewalld",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["check", "status", "firewall", "firewalld"],
        "description": "Check firewall status and rules",
        "category": "security",
        "commands": [
            "systemctl status firewalld",
            "firewall-cmd --list-all",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["add", "open", "port", "firewall"],
        "description": "Open a port in firewalld",
        "category": "security",
        "commands": [
            "firewall-cmd --permanent --add-port=<port>/tcp",
            "firewall-cmd --reload",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <port> with the port number. Add --zone=<zone> if not using default zone.",
    },
    {
        "keywords": ["remove", "close", "port", "firewall"],
        "description": "Close a port in firewalld",
        "category": "security",
        "commands": [
            "firewall-cmd --permanent --remove-port=<port>/tcp",
            "firewall-cmd --reload",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <port> with the port number.",
    },
    # Networking
    {
        "keywords": ["check", "network", "interfaces", "connections"],
        "description": "Check network interfaces and connections",
        "category": "networking",
        "commands": [
            "nmcli device status",
            "nmcli connection show",
            "ip addr show",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["restart", "network", "networkmanager"],
        "description": "Restart NetworkManager",
        "category": "networking",
        "commands": ["systemctl restart NetworkManager"],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "This may briefly interrupt network connectivity.",
    },
    {
        "keywords": ["set", "hostname"],
        "description": "Set system hostname",
        "category": "networking",
        "commands": ["hostnamectl set-hostname <new-hostname>"],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "Replace <new-hostname> with the desired hostname.",
    },
    {
        "keywords": ["check", "hostname"],
        "description": "Check current hostname",
        "category": "networking",
        "commands": ["hostnamectl"],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    # Storage
    {
        "keywords": ["check", "disk", "usage", "space"],
        "description": "Check disk usage",
        "category": "storage",
        "commands": ["df -hT", "du -sh /* 2>/dev/null | sort -rh | head -10"],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["list", "lvm", "volumes", "logical"],
        "description": "List LVM volumes and groups",
        "category": "storage",
        "commands": ["pvs", "vgs", "lvs"],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["check", "mounts", "fstab", "mounted"],
        "description": "Check mounted filesystems",
        "category": "storage",
        "commands": ["mount | column -t", "cat /etc/fstab"],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    # Services
    {
        "keywords": ["list", "services", "running"],
        "description": "List all running services",
        "category": "services",
        "commands": ["systemctl list-units --type=service --state=running"],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["list", "services", "enabled"],
        "description": "List all enabled services",
        "category": "services",
        "commands": ["systemctl list-unit-files --type=service --state=enabled"],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["enable", "service"],
        "description": "Enable and start a service",
        "category": "services",
        "commands": [
            "systemctl enable <service_name>",
            "systemctl start <service_name>",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <service_name> with the actual service name.",
    },
    {
        "keywords": ["disable", "service"],
        "description": "Disable and stop a service",
        "category": "services",
        "commands": [
            "systemctl stop <service_name>",
            "systemctl disable <service_name>",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <service_name> with the actual service name.",
    },
    {
        "keywords": ["restart", "service"],
        "description": "Restart a service",
        "category": "services",
        "commands": ["systemctl restart <service_name>"],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <service_name> with the actual service name.",
    },
    # Users
    {
        "keywords": ["list", "users"],
        "description": "List system users",
        "category": "users",
        "commands": [
            "cat /etc/passwd",
            "awk -F: '$3 >= 1000 {print $1}' /etc/passwd",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "Second command shows only regular (non-system) users.",
    },
    {
        "keywords": ["check", "password", "policy", "aging"],
        "description": "Check password aging policy",
        "category": "users",
        "commands": [
            "cat /etc/login.defs | grep -E '^PASS_'",
            "chage -l <username>",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "Replace <username> with the actual username.",
    },
    # Packages
    {
        "keywords": ["check", "updates", "available"],
        "description": "Check for available package updates",
        "category": "packages",
        "commands": ["yum check-update || true"],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "Use 'dnf check-update' on RHEL 8+.",
    },
    {
        "keywords": ["list", "installed", "packages"],
        "description": "List installed packages",
        "category": "packages",
        "commands": ["rpm -qa --last | head -20"],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "Shows 20 most recently installed packages.",
    },
    # Performance / Tuned
    {
        "keywords": ["check", "tuned", "profile"],
        "description": "Check current tuned profile",
        "category": "performance",
        "commands": [
            "tuned-adm active",
            "tuned-adm list",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["set", "tuned", "profile"],
        "description": "Set a tuned performance profile",
        "category": "performance",
        "commands": ["tuned-adm profile <profile_name>"],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <profile_name> with the desired profile (e.g. throughput-performance, latency-performance).",
    },
    # System
    {
        "keywords": ["check", "system", "status", "overview"],
        "description": "Show system status overview",
        "category": "system",
        "commands": [
            "hostnamectl",
            "uptime",
            "free -h",
            "df -hT /",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["check", "uptime"],
        "description": "Check system uptime",
        "category": "system",
        "commands": ["uptime"],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["check", "memory", "ram"],
        "description": "Check memory usage",
        "category": "system",
        "commands": ["free -h", "cat /proc/meminfo | head -5"],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["reboot", "system", "restart"],
        "description": "Reboot the system",
        "category": "system",
        "commands": ["systemctl reboot"],
        "risk_level": "high",
        "requires_reboot": True,
        "notes": "WARNING: This will immediately reboot the system.",
    },
    # Time
    {
        "keywords": ["check", "timezone", "time"],
        "description": "Check current timezone and time settings",
        "category": "time",
        "commands": ["timedatectl"],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["set", "timezone"],
        "description": "Set system timezone",
        "category": "time",
        "commands": ["timedatectl set-timezone <timezone>"],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "Replace <timezone> with the desired timezone (e.g. America/New_York). List available with 'timedatectl list-timezones'.",
    },
    {
        "keywords": ["check", "chrony", "ntp", "time", "sync"],
        "description": "Check chrony/NTP time synchronization",
        "category": "time",
        "commands": [
            "chronyc tracking",
            "chronyc sources -v",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    # Logging
    {
        "keywords": ["check", "journal", "logs", "journalctl"],
        "description": "Check recent system journal logs",
        "category": "logging",
        "commands": ["journalctl -xe --no-pager | tail -50"],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["check", "rsyslog", "syslog"],
        "description": "Check rsyslog configuration and status",
        "category": "logging",
        "commands": [
            "systemctl status rsyslog",
            "cat /etc/rsyslog.conf",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["check", "boot", "logs", "dmesg"],
        "description": "Check boot and kernel ring buffer logs",
        "category": "logging",
        "commands": [
            "journalctl -b --no-pager | tail -50",
            "dmesg | tail -30",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["check", "failed", "services", "errors"],
        "description": "Check failed systemd services",
        "category": "logging",
        "commands": [
            "systemctl --failed",
            "journalctl -p err -b --no-pager | tail -30",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["configure", "logrotate"],
        "description": "Check and configure logrotate",
        "category": "logging",
        "commands": [
            "cat /etc/logrotate.conf",
            "ls /etc/logrotate.d/",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "Edit /etc/logrotate.d/<service> to add custom rotation rules.",
    },
    {
        "keywords": ["persistent", "journal", "journald"],
        "description": "Make journald logs persistent across reboots",
        "category": "logging",
        "commands": [
            "mkdir -p /var/log/journal",
            "systemd-tmpfiles --create --prefix /var/log/journal",
            "sed -i 's/^#Storage=.*/Storage=persistent/' /etc/systemd/journald.conf",
            "systemctl restart systemd-journald",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Logs will now persist in /var/log/journal/.",
    },
    # Networking - Static IP
    {
        "keywords": ["set", "static", "ip", "address"],
        "description": "Set a static IP address on a connection",
        "category": "networking",
        "commands": [
            "nmcli connection modify <connection_name> ipv4.addresses <ip>/<prefix>",
            "nmcli connection modify <connection_name> ipv4.gateway <gateway>",
            "nmcli connection modify <connection_name> ipv4.method manual",
            "nmcli connection up <connection_name>",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <connection_name>, <ip>/<prefix> (e.g. 192.168.1.100/24), and <gateway>.",
    },
    {
        "keywords": ["set", "dhcp", "ip", "automatic"],
        "description": "Set connection to use DHCP",
        "category": "networking",
        "commands": [
            "nmcli connection modify <connection_name> ipv4.method auto",
            "nmcli connection modify <connection_name> ipv4.addresses ''",
            "nmcli connection modify <connection_name> ipv4.gateway ''",
            "nmcli connection up <connection_name>",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <connection_name> with the actual connection name.",
    },
    {
        "keywords": ["set", "dns", "nameserver"],
        "description": "Set DNS nameservers on a connection",
        "category": "networking",
        "commands": [
            "nmcli connection modify <connection_name> ipv4.dns '<dns1> <dns2>'",
            "nmcli connection up <connection_name>",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <connection_name> and <dns1> <dns2> (e.g. 8.8.8.8 8.8.4.4).",
    },
    {
        "keywords": ["check", "dns", "resolv"],
        "description": "Check DNS configuration",
        "category": "networking",
        "commands": [
            "cat /etc/resolv.conf",
            "nmcli device show | grep DNS",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["check", "routes", "routing", "table"],
        "description": "Check routing table",
        "category": "networking",
        "commands": [
            "ip route show",
            "nmcli connection show <connection_name> | grep route",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "Replace <connection_name> or remove the second command for a general check.",
    },
    {
        "keywords": ["add", "static", "route"],
        "description": "Add a static route",
        "category": "networking",
        "commands": [
            "nmcli connection modify <connection_name> +ipv4.routes '<network>/<prefix> <gateway>'",
            "nmcli connection up <connection_name>",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <connection_name>, <network>/<prefix> (e.g. 10.0.0.0/8), and <gateway>.",
    },
    {
        "keywords": ["configure", "bonding", "bond", "network"],
        "description": "Configure network bonding (active-backup)",
        "category": "networking",
        "commands": [
            "nmcli connection add type bond con-name bond0 ifname bond0 bond.options 'mode=active-backup,miimon=100'",
            "nmcli connection add type ethernet con-name bond0-slave1 ifname <nic1> master bond0",
            "nmcli connection add type ethernet con-name bond0-slave2 ifname <nic2> master bond0",
            "nmcli connection up bond0",
        ],
        "risk_level": "high",
        "requires_reboot": False,
        "notes": "Replace <nic1> and <nic2> with actual interface names. Modes: active-backup, balance-rr, 802.3ad (LACP).",
    },
    {
        "keywords": ["configure", "vlan", "network"],
        "description": "Create a VLAN interface",
        "category": "networking",
        "commands": [
            "nmcli connection add type vlan con-name vlan<id> dev <interface> id <id>",
            "nmcli connection up vlan<id>",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <interface> with the parent NIC and <id> with the VLAN ID.",
    },
    {
        "keywords": ["configure", "bridge", "network"],
        "description": "Create a network bridge",
        "category": "networking",
        "commands": [
            "nmcli connection add type bridge con-name br0 ifname br0",
            "nmcli connection add type ethernet con-name br0-slave ifname <interface> master br0",
            "nmcli connection up br0",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <interface> with the physical NIC to add to the bridge.",
    },
    {
        "keywords": ["check", "ports", "listening", "open"],
        "description": "Check listening ports and connections",
        "category": "networking",
        "commands": [
            "ss -tulnp",
            "ss -s",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["test", "connectivity", "ping", "network"],
        "description": "Test network connectivity",
        "category": "networking",
        "commands": [
            "ping -c 3 8.8.8.8",
            "ping -c 3 google.com",
            "ip route get 8.8.8.8",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    # Firewall - additional
    {
        "keywords": ["add", "firewall", "service"],
        "description": "Allow a service through the firewall",
        "category": "security",
        "commands": [
            "firewall-cmd --permanent --add-service=<service_name>",
            "firewall-cmd --reload",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <service_name> (e.g. http, https, ssh, nfs). List available: firewall-cmd --get-services.",
    },
    {
        "keywords": ["remove", "firewall", "service"],
        "description": "Remove a service from firewall",
        "category": "security",
        "commands": [
            "firewall-cmd --permanent --remove-service=<service_name>",
            "firewall-cmd --reload",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <service_name> with the service to remove.",
    },
    {
        "keywords": ["list", "firewall", "zones"],
        "description": "List all firewall zones and active zones",
        "category": "security",
        "commands": [
            "firewall-cmd --get-active-zones",
            "firewall-cmd --list-all-zones",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["add", "firewall", "rich", "rule"],
        "description": "Add a firewall rich rule",
        "category": "security",
        "commands": [
            "firewall-cmd --permanent --add-rich-rule='rule family=\"ipv4\" source address=\"<source_ip>\" port protocol=\"tcp\" port=\"<port>\" accept'",
            "firewall-cmd --reload",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <source_ip> and <port>. Use reject/drop instead of accept to block.",
    },
    {
        "keywords": ["enable", "masquerade", "nat", "firewall"],
        "description": "Enable IP masquerading (NAT) on firewall",
        "category": "security",
        "commands": [
            "firewall-cmd --permanent --add-masquerade",
            "firewall-cmd --reload",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Enables NAT for outgoing traffic. Useful for routing/gateway setups.",
    },
    {
        "keywords": ["forward", "port", "firewall"],
        "description": "Configure port forwarding in firewall",
        "category": "security",
        "commands": [
            "firewall-cmd --permanent --add-forward-port=port=<src_port>:proto=tcp:toport=<dst_port>:toaddr=<dst_ip>",
            "firewall-cmd --reload",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <src_port>, <dst_port>, and <dst_ip>.",
    },
    # Storage - management
    {
        "keywords": ["create", "lvm", "logical", "volume"],
        "description": "Create LVM logical volume",
        "category": "storage",
        "commands": [
            "pvcreate /dev/<disk>",
            "vgcreate <vg_name> /dev/<disk>",
            "lvcreate -L <size>G -n <lv_name> <vg_name>",
            "mkfs.xfs /dev/<vg_name>/<lv_name>",
        ],
        "risk_level": "high",
        "requires_reboot": False,
        "notes": "Replace <disk>, <vg_name>, <lv_name>, <size>. This will destroy data on the disk.",
    },
    {
        "keywords": ["extend", "lvm", "logical", "volume", "grow"],
        "description": "Extend an LVM logical volume",
        "category": "storage",
        "commands": [
            "lvextend -L +<size>G /dev/<vg_name>/<lv_name>",
            "xfs_growfs /dev/<vg_name>/<lv_name>",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <size>, <vg_name>, <lv_name>. Use resize2fs instead of xfs_growfs for ext4.",
    },
    {
        "keywords": ["add", "fstab", "mount", "persistent"],
        "description": "Add a persistent mount to /etc/fstab",
        "category": "storage",
        "commands": [
            "blkid /dev/<device>",
            "mkdir -p <mount_point>",
            "echo 'UUID=<uuid> <mount_point> <fstype> defaults 0 0' >> /etc/fstab",
            "mount -a",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <device>, <mount_point>, <uuid>, <fstype>. Use blkid to find the UUID first.",
    },
    {
        "keywords": ["mount", "nfs", "share"],
        "description": "Mount an NFS share",
        "category": "storage",
        "commands": [
            "mkdir -p <mount_point>",
            "mount -t nfs <server>:<remote_path> <mount_point>",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <server>, <remote_path>, <mount_point>. Add to /etc/fstab for persistence.",
    },
    {
        "keywords": ["export", "nfs", "share", "configure"],
        "description": "Configure an NFS export",
        "category": "storage",
        "commands": [
            "yum install -y nfs-utils",
            "echo '<directory> <client_ip>(rw,sync,no_root_squash)' >> /etc/exports",
            "exportfs -rav",
            "systemctl enable --now nfs-server",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <directory> and <client_ip>. Use no_root_squash carefully.",
    },
    {
        "keywords": ["check", "inodes", "inode"],
        "description": "Check inode usage on filesystems",
        "category": "storage",
        "commands": ["df -i"],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["check", "block", "devices", "disks", "lsblk"],
        "description": "List block devices and disk layout",
        "category": "storage",
        "commands": [
            "lsblk -f",
            "fdisk -l 2>/dev/null",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["create", "swap", "file"],
        "description": "Create a swap file",
        "category": "storage",
        "commands": [
            "dd if=/dev/zero of=/swapfile bs=1M count=<size_mb>",
            "chmod 600 /swapfile",
            "mkswap /swapfile",
            "swapon /swapfile",
            "echo '/swapfile none swap defaults 0 0' >> /etc/fstab",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <size_mb> with swap size in MB (e.g. 2048 for 2GB).",
    },
    {
        "keywords": ["check", "swap"],
        "description": "Check swap usage",
        "category": "storage",
        "commands": [
            "swapon --show",
            "free -h",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["disable", "swap", "off"],
        "description": "Disable swap",
        "category": "storage",
        "commands": [
            "swapoff -a",
            "sed -i '/swap/d' /etc/fstab",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Removes all swap entries from fstab. Verify with 'swapon --show'.",
    },
    # Users - management
    {
        "keywords": ["add", "create", "user"],
        "description": "Create a new user",
        "category": "users",
        "commands": [
            "useradd -m -s /bin/bash <username>",
            "passwd <username>",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <username>. Use -G <group> to add to supplementary groups.",
    },
    {
        "keywords": ["delete", "remove", "user"],
        "description": "Delete a user and their home directory",
        "category": "users",
        "commands": ["userdel -r <username>"],
        "risk_level": "high",
        "requires_reboot": False,
        "notes": "Replace <username>. The -r flag removes the home directory. Omit -r to keep it.",
    },
    {
        "keywords": ["lock", "user", "account"],
        "description": "Lock a user account",
        "category": "users",
        "commands": ["usermod -L <username>"],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <username>. Use 'usermod -U <username>' to unlock.",
    },
    {
        "keywords": ["unlock", "user", "account"],
        "description": "Unlock a user account",
        "category": "users",
        "commands": ["usermod -U <username>"],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <username>.",
    },
    {
        "keywords": ["add", "user", "group"],
        "description": "Add a user to a group",
        "category": "users",
        "commands": ["usermod -aG <group> <username>"],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <group> and <username>. The -a flag appends (does not remove existing groups).",
    },
    {
        "keywords": ["create", "group"],
        "description": "Create a new group",
        "category": "users",
        "commands": ["groupadd <group_name>"],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "Replace <group_name>.",
    },
    {
        "keywords": ["list", "groups", "user"],
        "description": "List groups for a user",
        "category": "users",
        "commands": [
            "id <username>",
            "groups <username>",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "Replace <username>.",
    },
    {
        "keywords": ["set", "password", "expiry", "chage"],
        "description": "Set password expiry policy for a user",
        "category": "users",
        "commands": [
            "chage -M 90 -m 7 -W 14 <username>",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <username>. -M max days, -m min days, -W warn days.",
    },
    {
        "keywords": ["expire", "password", "force", "reset"],
        "description": "Force a user to change password at next login",
        "category": "users",
        "commands": ["chage -d 0 <username>"],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <username>.",
    },
    {
        "keywords": ["check", "sudoers", "sudo"],
        "description": "Check sudoers configuration",
        "category": "users",
        "commands": [
            "cat /etc/sudoers",
            "ls -la /etc/sudoers.d/",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "Always use 'visudo' to edit sudoers safely.",
    },
    {
        "keywords": ["add", "sudo", "sudoers", "privileges"],
        "description": "Grant sudo privileges to a user",
        "category": "users",
        "commands": ["usermod -aG wheel <username>"],
        "risk_level": "high",
        "requires_reboot": False,
        "notes": "Replace <username>. On RHEL, the 'wheel' group grants sudo access.",
    },
    # Packages - management
    {
        "keywords": ["install", "package"],
        "description": "Install a package",
        "category": "packages",
        "commands": ["yum install -y <package_name>"],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <package_name>. Use 'dnf' on RHEL 8+.",
    },
    {
        "keywords": ["remove", "uninstall", "package"],
        "description": "Remove a package",
        "category": "packages",
        "commands": ["yum remove -y <package_name>"],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <package_name>. Use 'dnf' on RHEL 8+.",
    },
    {
        "keywords": ["update", "upgrade", "packages", "all"],
        "description": "Update all packages",
        "category": "packages",
        "commands": ["yum update -y"],
        "risk_level": "high",
        "requires_reboot": True,
        "notes": "Use 'dnf update -y' on RHEL 8+. May require reboot if kernel is updated.",
    },
    {
        "keywords": ["list", "repos", "repositories"],
        "description": "List configured package repositories",
        "category": "packages",
        "commands": [
            "yum repolist all",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "Use 'dnf repolist all' on RHEL 8+.",
    },
    {
        "keywords": ["enable", "repo", "repository"],
        "description": "Enable a package repository",
        "category": "packages",
        "commands": ["yum-config-manager --enable <repo_id>"],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <repo_id>. Use 'dnf config-manager --set-enabled <repo_id>' on RHEL 8+.",
    },
    {
        "keywords": ["disable", "repo", "repository"],
        "description": "Disable a package repository",
        "category": "packages",
        "commands": ["yum-config-manager --disable <repo_id>"],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <repo_id>. Use 'dnf config-manager --set-disabled <repo_id>' on RHEL 8+.",
    },
    {
        "keywords": ["clean", "cache", "yum", "dnf"],
        "description": "Clean package manager cache",
        "category": "packages",
        "commands": [
            "yum clean all",
            "rm -rf /var/cache/yum",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "Use 'dnf clean all' on RHEL 8+.",
    },
    {
        "keywords": ["search", "find", "package"],
        "description": "Search for a package",
        "category": "packages",
        "commands": ["yum search <keyword>"],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "Replace <keyword>. Use 'dnf search' on RHEL 8+.",
    },
    {
        "keywords": ["info", "package", "details"],
        "description": "Show package information",
        "category": "packages",
        "commands": ["yum info <package_name>"],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "Replace <package_name>. Use 'dnf info' on RHEL 8+.",
    },
    {
        "keywords": ["check", "package", "installed"],
        "description": "Check if a specific package is installed",
        "category": "packages",
        "commands": ["rpm -q <package_name>"],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "Replace <package_name>.",
    },
    {
        "keywords": ["list", "module", "streams", "dnf"],
        "description": "List available DNF module streams (RHEL 8+)",
        "category": "packages",
        "commands": ["dnf module list"],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "Only available on RHEL 8+.",
    },
    {
        "keywords": ["enable", "module", "stream", "dnf"],
        "description": "Enable a DNF module stream (RHEL 8+)",
        "category": "packages",
        "commands": [
            "dnf module enable <module_name>:<stream>",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <module_name> and <stream> (e.g. nodejs:18, php:8.1).",
    },
    # Security - SSH
    {
        "keywords": ["harden", "ssh", "secure"],
        "description": "Harden SSH configuration",
        "category": "security",
        "commands": [
            "sed -i 's/^#PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config",
            "sed -i 's/^#PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config",
            "sed -i 's/^#MaxAuthTries.*/MaxAuthTries 3/' /etc/ssh/sshd_config",
            "sed -i 's/^#ClientAliveInterval.*/ClientAliveInterval 300/' /etc/ssh/sshd_config",
            "sed -i 's/^#ClientAliveCountMax.*/ClientAliveCountMax 2/' /etc/ssh/sshd_config",
            "systemctl restart sshd",
        ],
        "risk_level": "high",
        "requires_reboot": False,
        "notes": "WARNING: Ensure you have key-based SSH access before disabling password auth. This disables root login and password authentication.",
    },
    {
        "keywords": ["check", "ssh", "config", "configuration"],
        "description": "Check SSH configuration",
        "category": "security",
        "commands": [
            "sshd -T | grep -iE 'permitrootlogin|passwordauthentication|maxauthtries|port|allowusers|allowgroups'",
            "systemctl status sshd",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["change", "ssh", "port"],
        "description": "Change SSH port",
        "category": "security",
        "commands": [
            "sed -i 's/^#Port 22/Port <new_port>/' /etc/ssh/sshd_config",
            "semanage port -a -t ssh_port_t -p tcp <new_port>",
            "firewall-cmd --permanent --add-port=<new_port>/tcp",
            "firewall-cmd --reload",
            "systemctl restart sshd",
        ],
        "risk_level": "high",
        "requires_reboot": False,
        "notes": "Replace <new_port>. Ensure SELinux and firewall are updated. Test before closing current session!",
    },
    {
        "keywords": ["generate", "ssh", "key", "keygen"],
        "description": "Generate an SSH key pair",
        "category": "security",
        "commands": ["ssh-keygen -t ed25519 -C '<comment>'"],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "Replace <comment> with an identifier (e.g. user@host). ed25519 is preferred over RSA.",
    },
    # Security - SELinux advanced
    {
        "keywords": ["selinux", "boolean", "list", "sebool"],
        "description": "List SELinux booleans",
        "category": "security",
        "commands": ["getsebool -a"],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "Use 'getsebool -a | grep <keyword>' to filter.",
    },
    {
        "keywords": ["set", "selinux", "boolean", "sebool"],
        "description": "Set an SELinux boolean",
        "category": "security",
        "commands": ["setsebool -P <boolean_name> on"],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <boolean_name>. The -P flag makes it persistent.",
    },
    {
        "keywords": ["selinux", "context", "label", "restorecon"],
        "description": "Restore SELinux file contexts",
        "category": "security",
        "commands": ["restorecon -Rv <path>"],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <path>. Recursively restores default SELinux labels.",
    },
    {
        "keywords": ["selinux", "port", "label", "semanage"],
        "description": "Add an SELinux port label",
        "category": "security",
        "commands": ["semanage port -a -t <type> -p tcp <port>"],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <type> (e.g. http_port_t) and <port>. List with 'semanage port -l'.",
    },
    {
        "keywords": ["selinux", "troubleshoot", "audit", "denials"],
        "description": "Troubleshoot SELinux denials",
        "category": "security",
        "commands": [
            "ausearch -m avc -ts recent",
            "sealert -a /var/log/audit/audit.log 2>/dev/null | head -50",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "Install setroubleshoot-server for sealert. Use audit2allow to generate policy modules.",
    },
    # Security - Audit
    {
        "keywords": ["check", "audit", "rules"],
        "description": "Check audit rules and status",
        "category": "security",
        "commands": [
            "auditctl -l",
            "systemctl status auditd",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["add", "audit", "rule", "watch"],
        "description": "Add an audit watch rule",
        "category": "security",
        "commands": [
            "auditctl -w <path> -p rwxa -k <key_name>",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <path> and <key_name>. Add to /etc/audit/rules.d/ for persistence.",
    },
    {
        "keywords": ["search", "audit", "log"],
        "description": "Search audit logs",
        "category": "security",
        "commands": ["ausearch -k <key_name> --interpret"],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "Replace <key_name>. Use -ts today for today's events.",
    },
    # Security - Crypto policies
    {
        "keywords": ["check", "crypto", "policy"],
        "description": "Check current crypto policy (RHEL 8+)",
        "category": "security",
        "commands": ["update-crypto-policies --show"],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["set", "crypto", "policy"],
        "description": "Set system-wide crypto policy (RHEL 8+)",
        "category": "security",
        "commands": ["update-crypto-policies --set <policy>"],
        "risk_level": "high",
        "requires_reboot": False,
        "notes": "Replace <policy> with DEFAULT, LEGACY, FUTURE, or FIPS. Affects SSH, TLS, etc.",
    },
    # Boot
    {
        "keywords": ["check", "default", "target", "runlevel"],
        "description": "Check default boot target (runlevel)",
        "category": "boot",
        "commands": ["systemctl get-default"],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["set", "default", "target", "graphical"],
        "description": "Set default boot target to graphical (GUI)",
        "category": "boot",
        "commands": ["systemctl set-default graphical.target"],
        "risk_level": "medium",
        "requires_reboot": True,
        "notes": "Takes effect on next reboot.",
    },
    {
        "keywords": ["set", "default", "target", "multi-user", "text", "cli"],
        "description": "Set default boot target to multi-user (text/CLI)",
        "category": "boot",
        "commands": ["systemctl set-default multi-user.target"],
        "risk_level": "medium",
        "requires_reboot": True,
        "notes": "Takes effect on next reboot. No GUI on boot.",
    },
    {
        "keywords": ["rebuild", "initramfs", "dracut"],
        "description": "Rebuild initramfs with dracut",
        "category": "boot",
        "commands": [
            "dracut --force --verbose",
        ],
        "risk_level": "high",
        "requires_reboot": True,
        "notes": "WARNING: Rebuilds initramfs for current kernel. Backup first if unsure.",
    },
    {
        "keywords": ["check", "grub", "kernel", "boot", "entries"],
        "description": "Check GRUB boot entries and default kernel",
        "category": "boot",
        "commands": [
            "grubby --default-kernel",
            "grubby --info=ALL",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["set", "default", "kernel", "boot"],
        "description": "Set the default boot kernel",
        "category": "boot",
        "commands": ["grubby --set-default /boot/vmlinuz-<kernel_version>"],
        "risk_level": "high",
        "requires_reboot": True,
        "notes": "Replace <kernel_version>. List kernels with 'grubby --info=ALL'.",
    },
    {
        "keywords": ["add", "kernel", "boot", "parameter", "grub"],
        "description": "Add a kernel boot parameter",
        "category": "boot",
        "commands": ["grubby --update-kernel=ALL --args='<parameter>=<value>'"],
        "risk_level": "high",
        "requires_reboot": True,
        "notes": "Replace <parameter>=<value>. Takes effect after reboot.",
    },
    {
        "keywords": ["remove", "kernel", "boot", "parameter", "grub"],
        "description": "Remove a kernel boot parameter",
        "category": "boot",
        "commands": ["grubby --update-kernel=ALL --remove-args='<parameter>'"],
        "risk_level": "high",
        "requires_reboot": True,
        "notes": "Replace <parameter>. Takes effect after reboot.",
    },
    # Subscriptions
    {
        "keywords": ["register", "subscription", "rhsm"],
        "description": "Register system with Red Hat Subscription Manager",
        "category": "subscriptions",
        "commands": [
            "subscription-manager register --username <username> --password <password>",
            "subscription-manager attach --auto",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <username> and <password> with your Red Hat credentials.",
    },
    {
        "keywords": ["check", "subscription", "status", "rhsm"],
        "description": "Check subscription status",
        "category": "subscriptions",
        "commands": [
            "subscription-manager status",
            "subscription-manager list --consumed",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["list", "subscription", "repos", "rhsm"],
        "description": "List available subscription repos",
        "category": "subscriptions",
        "commands": ["subscription-manager repos --list"],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "Use --list-enabled to show only enabled repos.",
    },
    {
        "keywords": ["enable", "subscription", "repo", "rhsm"],
        "description": "Enable a subscription repository",
        "category": "subscriptions",
        "commands": ["subscription-manager repos --enable=<repo_id>"],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <repo_id> (e.g. rhel-8-for-x86_64-baseos-rpms).",
    },
    {
        "keywords": ["unregister", "subscription", "rhsm"],
        "description": "Unregister system from Red Hat Subscription Manager",
        "category": "subscriptions",
        "commands": ["subscription-manager unregister"],
        "risk_level": "high",
        "requires_reboot": False,
        "notes": "WARNING: This removes all subscription entitlements.",
    },
    # Performance - additional
    {
        "keywords": ["check", "cpu", "info", "processor"],
        "description": "Check CPU information",
        "category": "performance",
        "commands": [
            "lscpu",
            "cat /proc/cpuinfo | grep 'model name' | head -1",
            "nproc",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["check", "io", "scheduler", "disk"],
        "description": "Check I/O scheduler for block devices",
        "category": "performance",
        "commands": [
            "cat /sys/block/*/queue/scheduler",
            "lsblk -d -o NAME,SCHED",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["set", "io", "scheduler"],
        "description": "Set I/O scheduler for a block device",
        "category": "performance",
        "commands": [
            "echo '<scheduler>' > /sys/block/<device>/queue/scheduler",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <scheduler> (none, mq-deadline, bfq, kyber) and <device> (e.g. sda). Runtime only.",
    },
    {
        "keywords": ["check", "ulimits", "limits"],
        "description": "Check current ulimits",
        "category": "performance",
        "commands": [
            "ulimit -a",
            "cat /etc/security/limits.conf",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["set", "ulimits", "limits", "nofile"],
        "description": "Set open file limits for a user",
        "category": "performance",
        "commands": [
            "echo '<username> soft nofile 65536' >> /etc/security/limits.conf",
            "echo '<username> hard nofile 65536' >> /etc/security/limits.conf",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <username>. User must re-login for changes to take effect.",
    },
    {
        "keywords": ["check", "numa", "topology"],
        "description": "Check NUMA topology",
        "category": "performance",
        "commands": [
            "numactl --hardware",
            "lscpu | grep -i numa",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "Install numactl if not present.",
    },
    {
        "keywords": ["check", "load", "top", "processes"],
        "description": "Check system load and top processes",
        "category": "performance",
        "commands": [
            "uptime",
            "ps aux --sort=-%cpu | head -10",
            "ps aux --sort=-%mem | head -10",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "Shows top 10 processes by CPU and memory.",
    },
    # System - additional
    {
        "keywords": ["check", "os", "release", "version"],
        "description": "Check OS release and version",
        "category": "system",
        "commands": [
            "cat /etc/redhat-release",
            "cat /etc/os-release",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["shutdown", "poweroff", "system"],
        "description": "Shutdown the system",
        "category": "system",
        "commands": ["systemctl poweroff"],
        "risk_level": "high",
        "requires_reboot": False,
        "notes": "WARNING: This will immediately shut down the system.",
    },
    {
        "keywords": ["check", "hardware", "dmidecode"],
        "description": "Check hardware information",
        "category": "system",
        "commands": [
            "dmidecode -t system | head -20",
            "dmidecode -t memory | grep -E 'Size|Type|Speed' | head -20",
            "lspci | head -20",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "Requires root for dmidecode.",
    },
    # Time - additional
    {
        "keywords": ["enable", "ntp", "chrony", "sync"],
        "description": "Enable and configure NTP time synchronization",
        "category": "time",
        "commands": [
            "yum install -y chrony",
            "systemctl enable --now chronyd",
            "timedatectl set-ntp true",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "",
    },
    {
        "keywords": ["add", "ntp", "server", "chrony"],
        "description": "Add an NTP server to chrony",
        "category": "time",
        "commands": [
            "echo 'server <ntp_server> iburst' >> /etc/chrony.conf",
            "systemctl restart chronyd",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Replace <ntp_server> with the NTP server address.",
    },
    # Cron / Scheduled tasks
    {
        "keywords": ["list", "cron", "crontab", "scheduled"],
        "description": "List cron jobs",
        "category": "services",
        "commands": [
            "crontab -l",
            "ls -la /etc/cron.d/",
            "systemctl list-timers --all",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "Shows user crontab, system cron.d, and systemd timers.",
    },
    # Cockpit
    {
        "keywords": ["enable", "cockpit", "web", "console"],
        "description": "Enable Cockpit web console",
        "category": "services",
        "commands": [
            "yum install -y cockpit",
            "systemctl enable --now cockpit.socket",
            "firewall-cmd --permanent --add-service=cockpit",
            "firewall-cmd --reload",
        ],
        "risk_level": "medium",
        "requires_reboot": False,
        "notes": "Access Cockpit at https://<hostname>:9090.",
    },
    # SSSD / LDAP
    {
        "keywords": ["check", "sssd", "ldap", "status"],
        "description": "Check SSSD/LDAP authentication status",
        "category": "users",
        "commands": [
            "systemctl status sssd",
            "sssctl domain-list",
            "authselect current",
        ],
        "risk_level": "low",
        "requires_reboot": False,
        "notes": "",
    },
]


def match_local_command(prompt):
    """Match a user prompt against local command definitions using keyword scoring.

    Uses a ratio-based scoring: what fraction of the entry's keywords appear
    in the prompt. This prevents entries with few generic keywords from
    winning over more specific matches.

    Returns the best matching command definition as a dict matching the AI
    response JSON format, or None if no good match is found.
    """
    prompt_lower = prompt.lower()
    prompt_words = set(prompt_lower.split())

    best_match = None
    best_score = 0.0
    best_hits = 0

    for cmd in LOCAL_COMMANDS:
        keywords = cmd["keywords"]
        hits = 0
        for keyword in keywords:
            if keyword in prompt_words:
                hits += 2  # exact word match
            elif keyword in prompt_lower:
                hits += 1  # substring match

        if hits == 0:
            continue

        # Score = fraction of keywords matched (weighted hits / max possible)
        max_possible = len(keywords) * 2
        score = hits / max_possible

        if score > best_score or (score == best_score and hits > best_hits):
            best_score = score
            best_match = cmd
            best_hits = hits

    # Require at least 40% keyword coverage and at least 2 raw hits
    if best_score < 0.4 or best_hits < 2:
        return None

    return {
        "description": best_match["description"],
        "category": best_match["category"],
        "commands": list(best_match["commands"]),
        "risk_level": best_match["risk_level"],
        "requires_reboot": best_match["requires_reboot"],
        "notes": best_match.get("notes", ""),
    }
